#!/bin/bash

print_details() {
        filename=${arr[currentLine-1]}
        if [[ "$isDirectory" == "0" && "$currentLine" == "$lines" ]]
        then
                filename=$last
                links=$(ls -l $filename | cut -f2 -d' ')
                user=$(ls -l $filename | cut -f3 -d' ')
                group=$(ls -l $filename | cut -f4 -d' ')
                size=$(ls -l $filename | cut -f5 -d' ')
                modified=$(ls -l $filename | cut -f6-7 -d' ')
                year=$(ls --full-time $filename | cut -f6 -d' ' | cut -f1 -d'-')
        else
                links=$(ls -ld $filename | cut -f2 -d' ')
                user=$(ls -ld $filename | cut -f3 -d' ')
                group=$(ls -ld $filename | cut -f4 -d' ')
                size=$(ls -ld $filename | cut -f5 -d' ')
                modified=$(ls -ld $filename | cut -f6-7 -d' ')
                year=$(ls -ld --full-time $filename | cut -f6 -d' ' | cut -f1 -d'-' | head -4 | tail -1)
        fi
        echo -e "\r\e    Links: $links  Owner: $user  Group: $group  Size: $size  Modified: $modified $year"
}

change_cursor() {
        tput civis
        tput rmso
               
        tput cup $previousDetails
        echo -e "\r\e[0K " >&2
        tput cup $newDetails
        print_details
       
        previousDetails=$((newDetails))
        tput cup $u 26
       
        tput cnorm
}


if [ $# -gt 1 ]
then
        printf "Usage: showpath [ filename ]\n"
        exit 1
fi

if [[ ! -f $1 && ! -d $1 ]]
then
        echo "$1 is not a valid filename"
        exit 1
fi
tput clear
lines=0
filename=""
if [ "$1" != ""  ]
then
        filetype=$(ls -ld $1 | sed 's/./&\n/g' | head -1)
        if [ "$filetype" == "d" ]
        then
                cd $1
        else
                filename=$(echo $1 | sed 's/.*\///g')
                dir=$(echo $1 | sed 's/\/[^\/]*$//')
                cd $dir
        fi
fi
path=$(pwd)
command=""
u=0
isDirectory="0"
printf "  Owner   Group   Other   Filename\n"
printf "  -----   -----   -----   --------\n"
printf "\n"
echo "$(ls -ld / | cut -f1 -d' ' | sed 's/.$//' | sed 's/......./& /' | sed 's/..../& /' | sed 's/./& /g')" " /"
first="/"
declare -a arr
arr=$first
lines=$((lines+1))
printf "\n"
curPath="/"
declare -a args
args=$(echo $path | sed 's/.//' | tr '/' ' ')
for i in $(echo $path |  sed 's/.//' | tr '/' ' ')
do
        echo "$(ls -ld $curPath$i | cut -f1 -d' ' | sed 's/......./& /' | sed 's/..../& /' | sed 's/./& /g')" " $i"
        printf "\n"
        i=$i"/"
        curPath=$curPath$i
        lines=$((lines+1))
        arr+=($curPath)
done

if [[ "$filename" != "" && "$filetype" != "d" ]]
then
        echo "$(ls -l $filename | cut -f1 -d' ' | sed 's/......./& /' | sed 's/..../& /' | sed 's/./& /g')" " $filename"
        last=$curPath$filename
        arr+=($last)
        lines=$((lines+1))
        links=$(ls -l $filename | cut -f2 -d' ')
        user=$(ls -l $filename | cut -f3 -d' ')
        group=$(ls -l $filename | cut -f4 -d' ')
        size=$(ls -l $filename | cut -f5 -d' ')
        modified=$(ls -l $filename | cut -f6-7 -d' ')
        year=$(ls --full-time $filename | cut -f6 -d' ' | cut -f1 -d'-')
else
        isDirectory="1"
        links=$(ls -ld $filename | cut -f2 -d' ')
        user=$(ls -ld $filename | cut -f3 -d' ')
        group=$(ls -ld $filename | cut -f4 -d' ')
        size=$(ls -ld $filename | cut -f5 -d' ')
        modified=$(ls -ld $filename | cut -f6-7 -d' ')
        year=$(ls --full-time $filename | cut -f6 -d' ' | cut -f1 -d'-' | head -4 | tail -1)
fi     
       
lowestLevel=$(( (lines * 2) + 1))
previousDetails=$(( lowestLevel + 1))
newDetails=$(( lowestLevel + 1))
bottom=$(( lowestLevel ))
top=$(( 4 ))
u=$(( lowestLevel ))
  
currentLine=$(( lines ))
previousLine=$((currentLine))
       
stty -icanon min 0 time 0 -icrnl -echo
tput smkx

if [ "$isDirectory" == "1" ]
then
        # to print at proper line because last dir prints a newline and we don't want that here
        x=$((u+1))
        tput cup $x 26
        echo -e "\r\e    Links: $links  Owner: $user  Group: $group  Size: $size  Modified: $modified $year"
else    
        echo "  Links: $links  Owner: $user  Group: $group  Size: $size  Modified: $modified $year"
fi
       
printf "\n\n\n\n\n"    
       
rows=$(tput lines)
pos=$((rows-2))
tput cup $pos 0
       
echo -e "\r\e  Valid commands:  u(p)  d(own)  q(uit)"

tput cup $u 26
while true     
do
        read command
        case $command in
                u)
                        if [ $u -gt $top ]
                        then
                                u=$((u-2))
                                currentLine=$((currentLine-1))
                                newDetails=$((newDetails-2))
                                change_cursor
                        fi ;;
                d)
                        if [ $u -lt $bottom ]
                        then
                                u=$((u+2))
                                currentLine=$((currentLine+1))
                                newDetails=$((newDetails+2))
                                change_cursor
                        fi ;;
                q)
                        stty icanon icrnl echo
                        exit=$((pos+1))
                        tput cup $exit 0
                        exit 0 ;;
        esac
done
